#version: "3.7"
services:
  tortoisebot-ros2-real:
    image: invokelee/tortoisebot-ros2-real:1.0
    network_mode: host
    privileged: true
    hostname: ros2_real
    environment:    
      - DISPLAY=${DISPLAY}
      # - ROS_MASTER_URI=${ROS_MASTER_URI}
      # - ROS_HOSTNAME=${ROS_HOSTNAME}
    command:
      - /ros2_real/entrypoint.sh
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/mem:/dev/mem
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/shm:/dev/shm
      - ./tortoisebot-ros2-real/entrypoint.sh:/ros2_real/entrypoint.sh
      # - ./tortoisebot-ros2-real/camerav2_410x308.yaml:/root/.ros/camera_info/camerav2_410x308.yaml
      - real-static:/ros2_real/static/

  tortoisebot-ros2-slam-real:
    image: invokelee/tortoisebot-ros2-slam-real:1.0
    network_mode: host
    privileged: true
    hostname: ros2_slam
    restart: on-failure
    depends_on:
      - tortoisebot-ros2-real
    environment:    
      - DISPLAY=${DISPLAY}
      # - ROS_MASTER_URI=${ROS_MASTER_URI}
      # - ROS_HOSTNAME=${ROS_HOSTNAME}
    command:
      - /ros2_slam/entrypoint.sh
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/shm:/dev/shm
      - ./tortoisebot-ros2-slam-real/entrypoint.sh:/ros2_slam/entrypoint.sh

volumes:
  real-static:
